---
title: Submitting data to FLUXNET-CH4 V2
---

## How to submit data to FLUXNET-CH4 V2.0

If your data is not yet available through a regional network, below are instructions for data submission, along with information on required variables and site metadata.

1. DATA SUBMISSION: half hourly flux/met and BADM data (metadata and instrument info)

IF your site is registered in AmeriFlux, you have to upload the data through the AmeriFlux data portal (http://ameriflux.lbl.gov/data/upload-data/). 

IF your site is not registered in AmeriFlux but located in North or South America, please register your site to AmeriFlux before uploading the data (e.g., fill in the Site_General_Info BADM template (http://ameriflux.lbl.gov/sites/register-ameriflux-site/), or contact AmeriFlux Data Team (ameriflux-support@lbl.gov).

IF your site is part of the European FluxesDatabase Custer you have to upload the data in the database (http://www.europe-fluxdata.eu/) through the PI area.

IF your site is not registered in the above-mentioned databases but your institution is European, or your site is in Europe, Africa or Russia you have to use the European Database. Register your site at http://www.europe-fluxdata.eu/home/register-your-site or contact database@unitus.it for support.

For all the other cases (Asiaflux, Chinaflux, USCCC, OzFlux, LBA etc.) contact Dario Papale (darpap@unitus.it) to find the best solution using one of the regional networks as an entry point and get the site registered if needed.

Please note that all the sites must have an official FLUXNET code (in the form CC-###) that, if not already done, will be assigned by the database teams above. Please don’t create the code yourself because will not be recognized in the system.

The Biological, Ancillary, Disturbance and Metadata (BADM) protocol is standardized across AmeriFlux, EuroFlux, Fluxnet and other networks. The most updated BADM templates (e.g., disturbance, management, instrumentation, soil) can be downloaded here (http://ameriflux.lbl.gov/data/badm-data-templates/). All filled BADM templates can be submitted through the aforementioned pathways.

2. THE LIST OF VARIABLES REQUIRED 

Please ensure that you have all the BASE variables required for [ONEFlux processing](https://ameriflux.lbl.gov/data/flux-data-products/oneflux-processing/). That is:

* Required: CO2, FC, H, LE, WS, USTAR, TA, RH, PA, SW_IN (or PPFD_IN)
* Strongly encouraged: SC (if applicable), G, NETRAD, PPFD_IN, LW_IN, P, SWC, TS
* Additional suggested: WD, PPFD_DIF, PPFD_OUT, SW_DIF, SW_OUT, LW_OUT

You also need to submit CH4, FCH4, SCH4, as defined [here](https://ameriflux.lbl.gov/data/aboutdata/data-variables/). We also strongly suggest that you include predictors of CH4 flux including, but not limited to, WTD, SWC, TS.

Please contact us directly (Fa Li: fali2@stanford.edu) if you have any questions about submitting your data.