---
title: Project description
---

## FLUXNET-CH4 Community Product

FLUXNET-CH4 is an initiative led by the [Global Carbon Project](https://www.globalcarbonproject.org/), in close partnership with [AmeriFlux](https://ameriflux.lbl.gov/) and [EuroFlux](http://www.europe-fluxdata.eu/home), to compile a global database of eddy covariance (EC) methane flux measurements. Data are standardized, post-processed (i.e., partitioned and gap-filled), and released as FLUXNET-CH4 (Delwiche et al. 2021, Knox et al. 2019). [FLUXNET-CH4 Version 1.0](https://fluxnet.org/data/fluxnet-ch4-community-product/) includes data from 81 sites, representing freshwater, coastal, upland, natural, and managed ecosystems. The near continuous, high-frequency nature of EC measurements offers significant promise for improving our understanding of ecosystem-scale CH4 flux dynamics. FLUXNET-CH4 exists thanks to the hard work of the site teams who collected these data and their willingness to participate in the FLUXNET-CH4 effort. For FLUXNET-CH4 V1.0, please refer to the [Data Policy page](https://fluxnet.org/data/data-policy/) for data usage and acknowledgement requirements. Funding for the FLUXNET-CH4 initiative was provided by the Gordon and Betty Moore Foundation and the USGS Powell Center.